n1 = int(input('Digite um número: '))
n2 = int(input('Digite outro número: '))
print('Soma -> {} + {} = {}'.format(n1,n2,n1+n2)) 
print('Multiplicação -> {} x {} = {}'.format(n1,n2,n1*n2))
print('Divisão -> {} / {} = {:.3f}'.format(n1,n2,n1/n2))
print('Divisão Inteira -> {} // {} = {}'.format(n1,n2,n1//n2))
print('Potência -> {} ** {} = {}'.format(n1,n2,n1**n2))
