valor1 = int(input('Digite um valor para calcular a tabuada: '))
print('{} x 1 = {}'.format(valor1,valor1*1))
print('{} x 2 = {}'.format(valor1,valor1*2))
print('{} x 3 = {}'.format(valor1,valor1*3))
print('{} x 4 = {}'.format(valor1,valor1*4))
print('{} x 5 = {}'.format(valor1,valor1*5))
print('{} x 6 = {}'.format(valor1,valor1*6))
print('{} x 7 = {}'.format(valor1,valor1*7))
print('{} x 8 = {}'.format(valor1,valor1*8))
print('{} x 9 = {}'.format(valor1,valor1*9))
print('{} x 10 = {}'.format(valor1,valor1*10))

